### ISSUE TITLE
 Element '//*[contains(text(), 'Tips for getting started')]' is not present.

### ISSUE THREAD

**Issue by jxyk2007** [Priyanshu-hawk/ChatGPT-unofficial-api-selenium#13]
08/20/2024 02:58:26 PM - ERROR: # Element '//*[contains(text(), 'Log in with your OpenAI account to continue')]' is not present.
Already logged in
08/20/2024 02:58:48 PM - ERROR: # Element '//*[contains(text(), 'Tips for getting started')]' is not present.
08/20/2024 02:58:48 PM - ERROR: # Element '//*[contains(text(), 'Tips for getting started')]' is not present.
No guidlines found
Enter text:
08/20/2024 02:59:14 PM - ERROR: # Element '//*[@id='prompt-textarea']' is not present.
08/20/2024 02:59:14 PM - ERROR: # Element '//*[@id='prompt-textarea']' is not present.

**Comment by Priyanshu-hawk** [comment]
Hello @jxyk2007 take a new pull and retry.. Code has been update!!
