### ISSUE TITLE
Chrome Driver Download Issue @ Windows --> chrome_d_download.py/get_download_version(c_version)

### ISSUE THREAD

**Issue by debanjandhara** [Priyanshu-hawk/ChatGPT-unofficial-api-selenium#16]
**Description:**

In the function `get_download_version(c_version)` from `chrome_d_download.py`, there is an issue with detecting and downloading the correct version of Chromedriver, specifically for Windows. The function compares the current Chrome version (`c_version`) with the list of available Chromedriver versions fetched from the URL:

```python
def get_download_version(c_version):
    r = requests.get("https://chromedriver.storage.googleapis.com/?delimiter=/&prefix=")
    version_info = ET.fromstring(r.content)

    for i in version_info.iter('{http://doc.s3.amazonaws.com/2006-03-01}Prefix'):
        curr_version = i.text
        if curr_version != None:
            if front_version_extractor(c_version) == front_version_extractor(curr_version):
                return str(curr_version[:-1])
```

**Problem:**

Sometimes, the most recent version of Chrome does not match any of the versions listed in the Chromedriver storage. As a result, the function returns `None`, which leads to a `TypeError` when trying to construct the download URL, as shown below:

```bash
ChatGPT-unofficial-api-selenium\chrome_d_download.py:151: SyntaxWarning: invalid escape sequence '\S'
  todl = os.popen('reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version')
[+] Detected System: Windows
Downloading Chromedriver for your system of version: None
Traceback (most recent call last):
  File "D:\Debanjan\Projects\Personal Project Template\ChatGPT-unofficial-api-selenium\chrome_d_download.py", line 176, in <module>
    chromeDriverDownloader()
  File "D:\Debanjan\Projects\Personal Project Template\ChatGPT-unofficial-api-selenium\chrome_d_download.py", line 154, in chromeDriverDownloader 
    url = "https://chromedriver.storage.googleapis.com/"+get_download_version(vrsn)+"/chromedriver_win32.zip"
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```

**Workaround:**

A workaround is to modify the `get_download_version` function to return the current Chrome version (`c_version`) if no matching Chromedriver version is found. Here's the updated code:

```python
for i in version_info.iter('{http://doc.s3.amazonaws.com/2006-03-01}Prefix'):
    curr_version = i.text
    if curr_version != None:
        if front_version_extractor(c_version) == front_version_extractor(curr_version):
            return str(curr_version[:-1])
        else:
            return str(c_version)
```

This ensures that even if no match is found, it defaults to the current version (`c_version`), avoiding the `NoneType` error.

**Environment:**
- Windows OS
- Python version: Python 3.12.6
- Chrome version (`c_version`): 129.0.6668.100

**Comment by Priyanshu-hawk** [comment]
Hello @debanjandhara , Thankyou for pointing out the issue for windows, can yo create a Pull Request for the same, so i will test it and merge to main branch.
