### ISSUE TITLE
FileNotFoundError : when starting Chrome on 64-bit Windows

### ISSUE THREAD

**Issue by debanjandhara** [Priyanshu-hawk/ChatGPT-unofficial-api-selenium#17]
**Description:**

When attempting to start Chrome using the function `start_chrome()` from `chrome_handler.py` on a 64-bit Windows machine, a `FileNotFoundError` is raised. This occurs because the function `get_chrome_path()` only checks for the Chrome executable in the 32-bit installation directory (`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`), but on 64-bit systems, Chrome is often installed in the 64-bit directory (`C:\Program Files\Google\Chrome\Application\chrome.exe`).

### Error Details:

```bash
Traceback (most recent call last):
  File "D:\Debanjan\Projects\Personal Project Template\ChatGPT-unofficial-api-selenium\chrome_handler.py", line 20, in start_chrome
    subprocess.Popen([f'{chrome_path}','--remote-debugging-port=9222','--user-data-dir=chromedata'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

This error occurs because `get_chrome_path()` only checks for the 32-bit version of Chrome, and when Chrome is installed in the 64-bit path, it fails to locate the executable.

### Cause:

The current implementation of `get_chrome_path()` assumes that Chrome is installed in the 32-bit directory (`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`), which is valid for 32-bit installations. However, on 64-bit systems, Chrome is more commonly installed in the 64-bit directory (`C:\Program Files\Google\Chrome\Application\chrome.exe`).

### Proposed Solution:

The `get_chrome_path()` function should be updated to check both the 32-bit and 64-bit installation paths. Here is the proposed updated function:

```python
import os
import platform

def get_chrome_path():
    os_name = platform.system().lower()

    if os_name == "windows":
        # Paths for 32-bit and 64-bit installations of Chrome
        chrome_32bit_path = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
        chrome_64bit_path = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"

        # Check if the 32-bit Chrome exists
        if os.path.exists(chrome_32bit_path):
            return chrome_32bit_path
        # If not, check for the 64-bit version
        elif os.path.exists(chrome_64bit_path):
            return chrome_64bit_path
        else:
            raise FileNotFoundError("Chrome executable not found in either 32-bit or 64-bit directories.")
    
    elif os_name == "darwin":
        # macOS path
        return "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    
    elif os_name == "linux":
        # Linux path
        return "/usr/bin/google-chrome"
    
    else:
        raise Exception(f"Unsupported OS: {os_name}")
```

### Solution Explanation:

- The updated `get_chrome_path()` function now checks both the 32-bit and 64-bit installation directories for Chrome (`Program Files (x86)` and `Program Files`).
- If the 32-bit executable is not found, the function checks the 64-bit directory and returns the correct path if it exists.
- If neither executable is found, a `FileNotFoundError` is raised with a clear error message.

**Comment by Priyanshu-hawk** [comment]
Hello @debanjandhara , Thankyou for pointing out the issue for windows, pls add this and #16 in same PR. i will test it and merge to main.
