### ISSUE TITLE
ChatGPT Responce : from Raw Text to Formatted Markdown Format [Clipboard is used]

### ISSUE THREAD

**Issue by debanjandhara** [Priyanshu-hawk/ChatGPT-unofficial-api-selenium#19]
![image](https://github.com/user-attachments/assets/28c46533-5dbb-4b16-8402-b083fa115c56)

I have the code ready for it, can I just show you ? then you'll merge it....

**Comment by Priyanshu-hawk** [comment]
Yeah @debanjandhara , Create a PR. i'll check the code.

**Comment by debanjandhara** [comment]
Hi Priyanshu, I'm encountering a few issues:  

- The ChatGPT website doesn't respond unless it's in focus (this behavior is the same for your function as well) [needs discussion].  
- I've enabled text capture in canvas mode.  
- The overlay for login has been handled.  

Could you share your email? Alternatively, I've also messaged you on LinkedIn. Feel free to connect whenever it suits you!

**Comment by Priyanshu-hawk** [comment]
Sure, We can connect over linkedin @debanjandhara

**Comment by Priyanshu-hawk** [comment]
Pull #20 

With Browser Extension -
https://chromewebstore.google.com/detail/always-active-window-alwa/ehllkhjndgnlokhomdlhgbineffifcbj?utm_source=chatgpt.com
