### ISSUE TITLE
No such file or directory: 'google-chrome'

### ISSUE THREAD

**Issue by godsbball** [Priyanshu-hawk/ChatGPT-unofficial-api-selenium#7]
```bash
[burst@burst ChatGPT-unofficial-api-selenium]$ python chrome_d_download.py
[+] Detected System: Linux
[-]Error Found: [Errno 2] No such file or directory: 'google-chrome'
[+] Google Chrome is not installed, Please install it!! - https://www.google.com/chrome/
```

**Comment by Priyanshu-hawk** [comment]
Pls Download / Install google-chrome first. 

For Linux :- 
1. Download Google Chrome - https://www.google.com/chrome/ or https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
2. install Google Chrome - sudo dpkg -i google-chrome-stable_current_amd64.deb

Now run the api_backend.py again
