### ISSUE TITLE
Selenium cannot find the button.

### ISSUE THREAD

**Issue by alexnet123** [Priyanshu-hawk/ChatGPT-unofficial-api-selenium#9]
05/18/2024 05:15:08 PM - ERROR: # Element '//*[contains(text(), 'Log in with your OpenAI account to continue')]' is not present.
Already logged in
05/18/2024 05:15:31 PM - ERROR: # Element '//*[contains(text(), 'Tips for getting started')]' is not present.
05/18/2024 05:15:31 PM - ERROR: # Element '//*[contains(text(), 'Tips for getting started')]' is not present.
No guidlines found
Enter text: hello
05/18/2024 05:16:02 PM - ERROR: # Element '//*[@data-testid='send-button']' is not present.
05/18/2024 05:16:02 PM - ERROR: # Element '//*[@data-testid='send-button']' is not found.
Traceback (most recent call last):
  File "/home/alex/test/cs/ChatGPT-unofficial-api-selenium/api_backend.py", line 127, in <module>
    resp = make_gpt_request(req)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/test/cs/ChatGPT-unofficial-api-selenium/api_backend.py", line 94, in make_gpt_request
    send_btn.click()
    ^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'click'

**Comment by Priyanshu-hawk** [comment]
yeah.. UI has been updated in chatgpt.. i'll release the patch soon.

**Comment by Priyanshu-hawk** [comment]
Try taking a pull and run the code it is now working!!
